nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['http://localhost:5173', 'https://favospace.fr']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization', 'Link']
        max_age: 3600
    paths:
        '^/':  # Pour toutes les routes
            allow_origin: ['http://localhost:5173', 'https://favospace.fr']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: false
            max_age: 3600
